# Generated by Django 6.0.8 on 2026-09-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0021_grant_offers_finalize_to_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entra_object_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='entra_tenant_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='local_login_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('entra_object_id__gt', '')), fields=('entra_tenant_id', 'entra_object_id'), name='unique_entra_identity'),
        ),
    ]
