# Generated by Django 6.0.8 on 2026-09-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0022_user_entra_object_id_user_entra_tenant_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_entra_identity',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('entra_object_id__gt', '')), fields=('tenant', 'entra_tenant_id', 'entra_object_id'), name='unique_entra_identity'),
        ),
    ]
