# Generated by Django 6.0.8 on 2026-09-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0029_backfill_imported_invoice_sent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerecord',
            name='email_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoicerecord',
            name='email_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentreminder',
            name='email_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentreminder',
            name='email_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
