# Generated by Django 6.0.8 on 2026-10-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0030_invoicerecord_email_error_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoicerecord',
            index=models.Index(fields=['tenant', '-invoice_date', '-generated_at'], name='idx_invrec_tenant_invdate'),
        ),
        migrations.AddIndex(
            model_name='invoicerecord',
            index=models.Index(fields=['contract', 'period_start', 'period_end'], name='idx_invrec_contract_period'),
        ),
    ]
