# Generated by Django 6.0.8 on 2026-09-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0052_contractattachment_source_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconfirmation',
            name='email_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderconfirmation',
            name='email_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
