# Generated by Django 6.0.8 on 2026-10-06 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0053_orderconfirmation_email_error_and_more'),
        ('tenants', '0023_remove_user_unique_entra_identity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardKpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_month', models.DateField(help_text='Monatserster des erfassten Monats')),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['year_month'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'year_month'), name='unique_dashboard_kpi_snapshot_per_month')],
            },
        ),
    ]
