# Generated by Django 6.0.8 on 2026-10-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0054_dashboardkpisnapshot'),
        ('customers', '0011_customer_payment_term_days'),
        ('tenants', '0023_remove_user_unique_entra_identity_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'status'], name='contract_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'updated_at'], name='contract_tenant_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'deal_won_date'], name='contract_tenant_dealwon_idx'),
        ),
    ]
