# Generated by Django 6.0.8 on 2026-10-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0015_incominginvoice_extraction_confidence'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='banktransaction',
            name='idx_txn_counterparty',
        ),
    ]
